
ingrediente_tipo_manual = {
    'feijão preto': 'leguminosa',
    'carne seca': 'proteína',
    'linguiça calabresa': 'proteína',
    'costelinha de porco': 'proteína',
    'bacon': 'gordura',
    'arroz': 'carboidrato',
    'couve': 'vegetal',
    'farofa': 'carboidrato',
    'alho': 'condimento',
    'cebola': 'condimento',
    'folha de louro': 'condimento',
    'tomate': 'vegetal',
    'peixe': 'proteína',
    'leite de coco': 'gordura',
    'azeite de dendê': 'gordura',
    'pimentão': 'vegetal',
    'coentro': 'condimento',
    'urucum': 'condimento',
    'feijão verde': 'leguminosa',
    'queijo coalho': 'laticínio',
    'pão': 'carboidrato',
    'camarão': 'proteína',
    'amendoim': 'outro',
    'castanha': 'outro',
    'mandioca': 'carboidrato',
    'frango': 'proteína',
    'açafrão': 'condimento',
    'bucho': 'proteína',
    'ovo': 'proteína',
    'banana': 'fruta',
    'farinha de mandioca': 'carboidrato',
    'sal grosso': 'condimento',
    'cenoura': 'vegetal',
    'ervilha': 'vegetal',
    'uva passa': 'fruta',
    'batata': 'carboidrato',
    'maionese': 'gordura',
    'fubá': 'carboidrato',
    'óleo': 'gordura',
    'massa de lasanha': 'carboidrato',
    'molho de tomate': 'vegetal',
    'presunto': 'proteína',
    'massa de pastel': 'carboidrato',
    'bacalhau': 'proteína',
    'polvilho': 'carboidrato',
    'requeijão': 'laticínio',
    'milho': 'vegetal',
    'hortelã': 'condimento',
    'trigo para kibe': 'carboidrato',
    'camarão seco': 'proteína',
    'barriga de porco': 'gordura',
    'farinha de trigo': 'carboidrato',
    'açúcar': 'condimento',
    'leite condensado': 'laticínio',
    'chocolate': 'condimento',
    'coco ralado': 'fruta',
    'gema de ovo': 'proteína',
    'fermento': 'condimento',
    'canela': 'condimento',
    'milho branco': 'carboidrato',
    'goiaba': 'fruta',
    'goma de tapioca': 'carboidrato',
    'flocão de milho': 'carboidrato',
    'açaí': 'fruta',
    'granola': 'carboidrato',
    'limão': 'fruta',
    'cachaça': 'outro'
}
